title: Blog Phim của Minh Bùi
author: Minh Bùi
email: buiminh2000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Đây là blog phim của Minh Bui

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: buiminh1995

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
